"""create initial schema

Revision ID: e60bbbb80e8c
Revises:
Create Date: 2026-06-06 02:04:23.268809
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e60bbbb80e8c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("rewritten_queries_json", sa.JSON(), nullable=True),
        sa.Column("route_json", sa.JSON(), nullable=True),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("abstention_reason", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("trace_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_runs")),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("cik", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("exchange", sa.String(length=64), nullable=True),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_cik"), "companies", ["cik"], unique=True)
    op.create_index(op.f("ix_companies_ticker"), "companies", ["ticker"], unique=True)
    op.create_table(
        "eval_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected_tickers_json", sa.JSON(), nullable=True),
        sa.Column("expected_sections_json", sa.JSON(), nullable=True),
        sa.Column("relevant_chunk_ids_json", sa.JSON(), nullable=True),
        sa.Column("answer_type", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_questions")),
    )
    op.create_table(
        "eval_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eval_run_id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_results")),
    )
    op.create_index(
        op.f("ix_eval_results_eval_run_id"), "eval_results", ["eval_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_eval_results_metric_name"), "eval_results", ["metric_name"], unique=False
    )
    op.create_table(
        "retrieval_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("filters_json", sa.JSON(), nullable=True),
        sa.Column("retriever_variant", sa.String(length=128), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_runs")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("form_type", sa.String(length=32), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("period_end_date", sa.Date(), nullable=True),
        sa.Column("accession_number", sa.String(length=64), nullable=False),
        sa.Column("primary_document_url", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("sha256_hash", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_documents_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        op.f("ix_documents_accession_number"), "documents", ["accession_number"], unique=False
    )
    op.create_index(op.f("ix_documents_company_id"), "documents", ["company_id"], unique=False)
    op.create_index(op.f("ix_documents_filing_date"), "documents", ["filing_date"], unique=False)
    op.create_index(op.f("ix_documents_form_type"), "documents", ["form_type"], unique=False)
    op.create_table(
        "financial_facts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("concept", sa.String(length=256), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_period", sa.String(length=16), nullable=True),
        sa.Column("form_type", sa.String(length=32), nullable=True),
        sa.Column("accession_number", sa.String(length=64), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_financial_facts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_facts")),
    )
    op.create_index(
        op.f("ix_financial_facts_accession_number"),
        "financial_facts",
        ["accession_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_facts_company_id"), "financial_facts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_financial_facts_concept"), "financial_facts", ["concept"], unique=False
    )
    op.create_index(
        op.f("ix_financial_facts_fiscal_year"), "financial_facts", ["fiscal_year"], unique=False
    )
    op.create_index(
        op.f("ix_financial_facts_form_type"), "financial_facts", ["form_type"], unique=False
    )
    op.create_index(
        op.f("ix_financial_facts_period_end"), "financial_facts", ["period_end"], unique=False
    )
    op.create_index(op.f("ix_financial_facts_ticker"), "financial_facts", ["ticker"], unique=False)
    op.create_table(
        "document_elements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("element_type", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=True),
        sa.Column("json_payload", sa.JSON(), nullable=True),
        sa.Column("bbox", sa.JSON(), nullable=True),
        sa.Column("reading_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_elements_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_elements")),
    )
    op.create_index(
        op.f("ix_document_elements_document_id"), "document_elements", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_elements_element_type"),
        "document_elements",
        ["element_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_elements_section"), "document_elements", ["section"], unique=False
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("element_id", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunk_type", sa.String(length=64), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["element_id"],
            ["document_elements.id"],
            name=op.f("fk_chunks_element_id_document_elements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
    )
    op.create_index(op.f("ix_chunks_chunk_type"), "chunks", ["chunk_type"], unique=False)
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)
    op.create_index(op.f("ix_chunks_element_id"), "chunks", ["element_id"], unique=False)
    op.create_index(op.f("ix_chunks_section"), "chunks", ["section"], unique=False)
    op.create_table(
        "citations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer_run_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("citation_text", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_run_id"],
            ["answer_runs.id"],
            name=op.f("fk_citations_answer_run_id_answer_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunks.id"], name=op.f("fk_citations_chunk_id_chunks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citations")),
    )
    op.create_index(
        op.f("ix_citations_answer_run_id"), "citations", ["answer_run_id"], unique=False
    )
    op.create_index(op.f("ix_citations_chunk_id"), "citations", ["chunk_id"], unique=False)
    op.create_index(op.f("ix_citations_section"), "citations", ["section"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("vector_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_embeddings_chunk_id_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
    )
    op.create_index(op.f("ix_embeddings_chunk_id"), "embeddings", ["chunk_id"], unique=False)
    op.create_table(
        "retrieval_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retrieval_run_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("dense_score", sa.Float(), nullable=True),
        sa.Column("sparse_score", sa.Float(), nullable=True),
        sa.Column("hybrid_score", sa.Float(), nullable=True),
        sa.Column("rerank_score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunks.id"], name=op.f("fk_retrieval_results_chunk_id_chunks")
        ),
        sa.ForeignKeyConstraint(
            ["retrieval_run_id"],
            ["retrieval_runs.id"],
            name=op.f("fk_retrieval_results_retrieval_run_id_retrieval_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_results")),
    )
    op.create_index(
        op.f("ix_retrieval_results_chunk_id"), "retrieval_results", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_retrieval_results_retrieval_run_id"),
        "retrieval_results",
        ["retrieval_run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_retrieval_results_retrieval_run_id"), table_name="retrieval_results")
    op.drop_index(op.f("ix_retrieval_results_chunk_id"), table_name="retrieval_results")
    op.drop_table("retrieval_results")
    op.drop_index(op.f("ix_embeddings_chunk_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_citations_section"), table_name="citations")
    op.drop_index(op.f("ix_citations_chunk_id"), table_name="citations")
    op.drop_index(op.f("ix_citations_answer_run_id"), table_name="citations")
    op.drop_table("citations")
    op.drop_index(op.f("ix_chunks_section"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_element_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_chunk_type"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_document_elements_section"), table_name="document_elements")
    op.drop_index(op.f("ix_document_elements_element_type"), table_name="document_elements")
    op.drop_index(op.f("ix_document_elements_document_id"), table_name="document_elements")
    op.drop_table("document_elements")
    op.drop_index(op.f("ix_financial_facts_ticker"), table_name="financial_facts")
    op.drop_index(op.f("ix_financial_facts_period_end"), table_name="financial_facts")
    op.drop_index(op.f("ix_financial_facts_form_type"), table_name="financial_facts")
    op.drop_index(op.f("ix_financial_facts_fiscal_year"), table_name="financial_facts")
    op.drop_index(op.f("ix_financial_facts_concept"), table_name="financial_facts")
    op.drop_index(op.f("ix_financial_facts_company_id"), table_name="financial_facts")
    op.drop_index(op.f("ix_financial_facts_accession_number"), table_name="financial_facts")
    op.drop_table("financial_facts")
    op.drop_index(op.f("ix_documents_form_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_filing_date"), table_name="documents")
    op.drop_index(op.f("ix_documents_company_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_accession_number"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("retrieval_runs")
    op.drop_index(op.f("ix_eval_results_metric_name"), table_name="eval_results")
    op.drop_index(op.f("ix_eval_results_eval_run_id"), table_name="eval_results")
    op.drop_table("eval_results")
    op.drop_table("eval_questions")
    op.drop_index(op.f("ix_companies_ticker"), table_name="companies")
    op.drop_index(op.f("ix_companies_cik"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("answer_runs")
    # ### end Alembic commands ###
